### ISSUE TITLE
Can cbgt use some sort of logging tags?

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgt#38]
In Sync Gateway, we use a [clog](https://github.com/couchbase/clog/blob/master/clog.go)-like logging utility that ships with Sync Gateway: https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/base/logging.go

Can cbgt use clog instead of log.Println()'s?

**Comment by steveyen** [comment]
cbgt should be already using clog all over the place instead of go's standard library log.  Examples...

https://github.com/couchbaselabs/cbgt/blob/master/manager.go#L24
https://github.com/couchbaselabs/cbgt/blob/master/manager_janitor.go#L22

And, to share the future plan thinking... I was thinking that this needs to one day change to allow the application using cbgt to optionally pass in some external log func callback, instead of having cbgt depend directly on clog.  So, it'd be more similar, one day, to...

https://github.com/couchbaselabs/cbgt/blob/master/rebalance/rebalance.go#L44

**Comment by tleyden** [comment]
Ah ok, thanks for the heads up.  

I just filed https://github.com/couchbase/clog/issues/1 which is related to this request.
